apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "am.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "am.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "am.name" . }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "am.name" . }}
        app.kubernetes.io/component: api
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
          env:
            {{- range $k, $v := .Values.api.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- if .Values.oidc.enabled }}
            - name: EAM_OIDC_ISSUER
              value: {{ .Values.oidc.issuer | quote }}
            - name: EAM_OIDC_AUDIENCE
              value: {{ .Values.oidc.audience | quote }}
            - name: EAM_AUTH_REQUIRED
              value: {{ .Values.oidc.authRequired | quote }}
            {{- end }}
            {{- if .Values.license.enabled }}
            - name: EAM_LICENSE_URL
              value: {{ .Values.license.url | quote }}
            - name: EAM_LICENSE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.license.secretRef.name }}
                  key: {{ .Values.license.secretRef.key }}
            {{- end }}
          volumeMounts:
            - name: overlays
              mountPath: /data/overlays
          livenessProbe:
            httpGet: { path: /v1/health, port: {{ .Values.api.port }} }
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet: { path: /v1/health, port: {{ .Values.api.port }} }
            periodSeconds: 10
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}

      volumes:
        - name: overlays
          {{- if .Values.overlays.pvc.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "am.fullname" . }}-overlays
          {{- else }}
          emptyDir: {}
          {{- end }}

---
{{- if .Values.overlays.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "am.fullname" . }}-overlays
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "am.labels" . | nindent 4 }}
spec:
  accessModes: [{{ .Values.overlays.pvc.accessMode }}]
  storageClassName: {{ .Values.overlays.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.overlays.pvc.size }}
{{- end }}
