apiVersion: v1
kind: Service
metadata:
  name: {{ include "am.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "am.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "am.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
